# Generated by Django 3.0.3 on 2020-03-03 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('birth_date', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('visit_date', models.CharField(max_length=30)),
            ],
        ),
    ]
