# Generated by Django 3.0.3 on 2020-03-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='visit_date',
        ),
    ]
