# Generated by Django 3.0.3 on 2020-03-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0003_auto_20200304_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
