# Generated by Django 3.0.3 on 2020-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0004_auto_20200304_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
