# Generated by Django 3.0.3 on 2020-03-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0006_auto_20200304_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(blank=True, max_length=30)),
                ('heart_rate', models.CharField(blank=True, max_length=30)),
                ('symptoms', models.CharField(blank=True, max_length=300)),
                ('experienced_before', models.CharField(blank=True, max_length=30)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(blank=True, max_length=30)),
                ('aditional_comments', models.CharField(blank=True, max_length=30)),
                ('diagnosis_date', models.DateField(max_length=30, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Patient')),
            ],
        ),
    ]
