# Generated by Django 3.0.4 on 2020-03-19 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0009_auto_20200310_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='images/', verbose_name='')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Diagnosis')),
            ],
        ),
    ]
