# Generated by Django 3.0.4 on 2020-03-19 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0010_auto_20200319_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Image'),
        ),
    ]
