# Generated by Django 3.0.4 on 2020-03-23 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0015_auto_20200323_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNOMED_Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('snomed_diagnosis', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
