# Generated by Django 3.0.4 on 2020-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0017_auto_20200323_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
