# Generated by Django 3.0.4 on 2020-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0018_auto_20200323_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
