# Generated by Django 3.0.4 on 2020-03-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CardioApp', '0019_auto_20200323_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='image',
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=5)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Image')),
                ('diagnosis', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Diagnosis')),
            ],
        ),
    ]
