# Generated by Django 3.0.4 on 2020-04-15 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CardioApp', '0020_auto_20200325_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardiogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardiogram', models.FileField(null=True, upload_to='cardiograms/', verbose_name='File')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CardioApp.Patient')),
            ],
        ),
    ]
